/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js}'],
  theme: {
    extend: {
      colors: {
        'primary':               '#2D4AAB',
        'primary-hover':         '#243D91',
        'primary-pressed':       '#1D3278',
        'primary-soft':          '#EEF3FF',
        'primary-muted':         '#DDE6FF',
        'primary-container':     '#EEF3FF',
        'on-primary':            '#ffffff',
        'on-primary-container':  '#2D4AAB',
        'on-primary-fixed':      '#1D3278',
        'primary-fixed':         '#DDE6FF',
        'primary-fixed-dim':     '#BFD0FF',
        'secondary':             '#2D4AAB',
        'secondary-container':   '#EEF3FF',
        'on-secondary':          '#ffffff',
        'on-secondary-container':'#2D4AAB',
        'secondary-fixed':       '#DDE6FF',
        'secondary-fixed-dim':   '#BFD0FF',
        'teal-accent':           '#5ED7C6',
        'orange-accent':         '#F2A65A',
        'success':               '#10B981',
        'warning':               '#EAB308',
        'danger':                '#EF4444',
        'info':                  '#3B82F6',
        'background':            '#FFFFFF',
        'surface':               '#FFFFFF',
        'surface-bright':        '#FFFFFF',
        'surface-subtle':        '#F7F9FC',
        'surface-dim':           '#E8EEF7',
        'surface-variant':       '#E8EEF7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#F7F9FC',
        'surface-container':     '#F2F5FA',
        'surface-container-high':'#E8EEF7',
        'surface-container-highest':'#DDE6FF',
        'on-surface':            '#1D2433',
        'on-surface-variant':    '#6B7280',
        'on-surface-muted':      '#6B7280',
        'on-background':         '#1D2433',
        'outline':               '#CBD5E1',
        'outline-variant':       '#E2E8F0',
        'outline-ghost':         'rgba(45, 74, 171, 0.12)',
        'inverse-surface':       '#1D2433',
        'inverse-on-surface':    '#F7F9FC',
        'error':                 '#EF4444',
        'error-container':       '#FEE2E2',
        'tertiary':              '#2D4AAB',
        'tertiary-container':    '#EEF3FF',
        'on-tertiary':           '#ffffff',
        'on-tertiary-container': '#2D4AAB',
        'tertiary-fixed':        '#DDE6FF',
        'tertiary-fixed-dim':    '#BFD0FF',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body':     ['Inter', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
        'label':    ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:  '0.5rem',
        xl:  '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      boxShadow: {
        card: '0 8px 24px rgba(24, 39, 75, 0.06)',
        'card-hover': '0 12px 32px rgba(24, 39, 75, 0.10)',
        floating: '0 16px 48px rgba(24, 39, 75, 0.12)',
      },
    },
  },
  plugins: [],
}
