/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js}'],
  theme: {
    extend: {
      colors: {
        'primary':               '#000000',
        'primary-container':     '#131B2E',
        'on-primary':            '#ffffff',
        'on-primary-container':  '#7c839b',
        'on-primary-fixed':      '#131b2e',
        'primary-fixed':         '#dae2fd',
        'primary-fixed-dim':     '#bec6e0',
        'secondary':             '#006a61',
        'secondary-container':   '#86f2e4',
        'on-secondary':          '#ffffff',
        'on-secondary-container':'#006f66',
        'secondary-fixed':       '#89f5e7',
        'secondary-fixed-dim':   '#6bd8cb',
        'background':            '#f7f9fb',
        'surface':               '#f7f9fb',
        'surface-bright':        '#f7f9fb',
        'surface-dim':           '#d8dadc',
        'surface-variant':       '#e0e3e5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container':     '#eceef0',
        'surface-container-high':'#e6e8ea',
        'surface-container-highest':'#e0e3e5',
        'on-surface':            '#191c1e',
        'on-surface-variant':    '#45464d',
        'on-background':         '#191c1e',
        'outline':               '#76777d',
        'outline-variant':       '#c6c6cd',
        'inverse-surface':       '#2d3133',
        'inverse-on-surface':    '#eff1f3',
        'error':                 '#ba1a1a',
        'error-container':       '#ffdad6',
        'tertiary':              '#000000',
        'tertiary-container':    '#271901',
        'on-tertiary':           '#ffffff',
        'on-tertiary-container': '#98805d',
        'tertiary-fixed':        '#fcdeb5',
        'tertiary-fixed-dim':    '#dec29a',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body':     ['Inter', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
        'label':    ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:  '0.5rem',
        xl:  '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
